// <auto-generated />
using System;
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(BulkyDbContext))]
    [Migration("20250826104518_UpdatingSectionsTable")]
    partial class UpdatingSectionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky.Models.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Bulky.Models.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Bulky.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsHidden = false,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsHidden = false,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsHidden = false,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsHidden = false,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsHidden = false,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsHidden = false,
                            Name = "Children's Books"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsHidden = false,
                            Name = "History"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            IsHidden = false,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 9,
                            IsHidden = true,
                            Name = "Horror",
                            UpdatedAt = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Bulky.Models.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Tech City",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsHidden = false,
                            Name = "Tech Solution",
                            PhoneNumber = "6669990000",
                            PostalCode = "12121",
                            State = "IL",
                            StreetAddress = "123 Tech St"
                        },
                        new
                        {
                            Id = 2,
                            City = "Vid City",
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsHidden = false,
                            Name = "Vivid Books",
                            PhoneNumber = "7779990000",
                            PostalCode = "66666",
                            State = "IL",
                            StreetAddress = "999 Vid St"
                        },
                        new
                        {
                            Id = 3,
                            City = "Lala land",
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsHidden = false,
                            Name = "Readers Club",
                            PhoneNumber = "1113335555",
                            PostalCode = "99999",
                            State = "NY",
                            StreetAddress = "999 Main St"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Bulky.Models.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("PaymentDueDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("Bulky.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Harper Lee",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Harper Lee's Pulitzer Prize-winning novel explores racial injustice and moral growth in the American South. Through young Scout Finch's eyes, the story of her father, Atticus, defending a Black man unjustly accused, reveals themes of empathy, courage, and humanity. A timeless classic celebrated for its powerful narrative.",
                            DisplayOrder = 1,
                            ISBN = "978-0-06-112008-4",
                            IsHidden = false,
                            ListPrice = 18.989999999999998,
                            Price = 16.989999999999998,
                            Price100 = 14.99,
                            Price50 = 15.99,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 2,
                            Author = "F. Scott Fitzgerald",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "F. Scott Fitzgerald's iconic novel captures the Jazz Age's extravagance and disillusionment. Jay Gatsby's obsessive love for Daisy Buchanan and his pursuit of the American Dream unravel in a tragic tale of wealth, ambition, and unattainable desires, set against a backdrop of opulent Long Island parties.",
                            DisplayOrder = 2,
                            ISBN = "978-0-7432-7356-5",
                            IsHidden = false,
                            ListPrice = 16.989999999999998,
                            Price = 14.99,
                            Price100 = 12.99,
                            Price50 = 13.99,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "George Orwell's chilling dystopian novel depicts a totalitarian world of surveillance and control. Winston Smith's rebellion against the oppressive Party and Big Brother explores themes of freedom, truth, and individuality. A haunting, prophetic masterpiece that remains a cornerstone of modern literature.",
                            DisplayOrder = 3,
                            ISBN = "978-0-452-28423-4",
                            IsHidden = false,
                            ListPrice = 19.989999999999998,
                            Price = 17.989999999999998,
                            Price100 = 15.99,
                            Price50 = 16.989999999999998,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Frank Herbert",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Frank Herbert's epic sci-fi saga follows young Paul Atreides on the desert planet Arrakis, where the valuable spice melange shapes destinies. Blending politics, religion, and ecology, this richly detailed masterpiece explores power and survival in a gripping, universe-spanning narrative.",
                            DisplayOrder = 4,
                            ISBN = "978-0-441-17271-9",
                            IsHidden = false,
                            ListPrice = 22.989999999999998,
                            Price = 20.989999999999998,
                            Price100 = 18.989999999999998,
                            Price50 = 19.989999999999998,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Orson Scott Card",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Orson Scott Card's gripping sci-fi novel follows young Ender Wiggin, a brilliant strategist trained to lead humanity against an alien threat. Combining intense military tactics with deep moral questions, this coming-of-age tale explores leadership, sacrifice, and the cost of war.",
                            DisplayOrder = 5,
                            ISBN = "978-0-8125-5070-2",
                            IsHidden = false,
                            ListPrice = 18.989999999999998,
                            Price = 16.989999999999998,
                            Price100 = 14.99,
                            Price50 = 15.99,
                            Title = "Ender's Game"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Andy Weir",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Andy Weir's thrilling sci-fi novel follows astronaut Mark Watney, stranded on Mars after a mission goes awry. With ingenuity and humor, he fights to survive using science and resourcefulness. Praised for its scientific accuracy, this gripping tale of resilience captivates readers.",
                            DisplayOrder = 6,
                            ISBN = "978-0-8041-3902-1",
                            IsHidden = false,
                            ListPrice = 20.989999999999998,
                            Price = 18.989999999999998,
                            Price100 = 16.989999999999998,
                            Price50 = 17.989999999999998,
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Stieg Larsson",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stieg Larsson's gripping thriller follows journalist Mikael Blomkvist and hacker Lisbeth Salander as they unravel a decades-old mystery of murder and corruption in Sweden. This dark, suspenseful tale of revenge and intrigue became a global phenomenon for its complex characters.",
                            DisplayOrder = 7,
                            ISBN = "978-0-307-45454-1",
                            IsHidden = false,
                            ListPrice = 19.989999999999998,
                            Price = 17.989999999999998,
                            Price100 = 15.99,
                            Price50 = 16.989999999999998,
                            Title = "The Girl with the Dragon Tattoo"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Agatha Christie",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Agatha Christie's ingenious mystery, featuring Hercule Poirot, unravels the murder of a wealthy man in a quiet English village. Renowned for its shocking twist, this classic redefined the detective genre with its clever narrative and meticulous plotting.",
                            DisplayOrder = 8,
                            ISBN = "978-0-06-207349-4",
                            IsHidden = false,
                            ListPrice = 16.989999999999998,
                            Price = 14.99,
                            Price100 = 12.99,
                            Price50 = 13.99,
                            Title = "The Murder of Roger Ackroyd"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Agatha Christie",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Agatha Christie's chilling masterpiece traps ten strangers on an isolated island, where they face a murderer among them. With suspenseful pacing and a brilliant plot, this bestselling mystery keeps readers guessing until the shocking conclusion.",
                            DisplayOrder = 9,
                            ISBN = "978-0-06-207348-7",
                            IsHidden = false,
                            ListPrice = 17.989999999999998,
                            Price = 15.99,
                            Price100 = 13.99,
                            Price50 = 14.99,
                            Title = "And Then There Were None"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Jane Austen",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Jane Austen's timeless romance follows spirited Elizabeth Bennet and wealthy Mr. Darcy as they navigate love, pride, and societal expectations. With sharp wit and insightful social commentary, this beloved classic explores personal growth and enduring love in 19th-century England.",
                            DisplayOrder = 10,
                            ISBN = "978-0-14-143951-8",
                            IsHidden = false,
                            ListPrice = 15.99,
                            Price = 13.99,
                            Price100 = 11.99,
                            Price50 = 12.99,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Sarah J. Maas",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sarah J. Maas's enchanting romantasy follows Feyre, a human huntress drawn into a magical faerie world. Inspired by Beauty and the Beast, this steamy, action-packed tale blends romance and fantasy, captivating readers with its lush world and complex characters.",
                            DisplayOrder = 11,
                            ISBN = "978-1-61963-693-3",
                            IsHidden = false,
                            ListPrice = 21.989999999999998,
                            Price = 19.989999999999998,
                            Price100 = 0.0,
                            Price50 = 18.989999999999998,
                            Title = "A Court of Thorns and Roses"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Laura Hillenbrand",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laura Hillenbrand's gripping biography chronicles Louis Zamperini's extraordinary life—from Olympic athlete to WWII bombardier, POW, and survivor. This inspiring true story of resilience and redemption captures the indomitable human spirit against unimaginable adversity.",
                            DisplayOrder = 12,
                            ISBN = "978-0-8129-8187-5",
                            IsHidden = false,
                            ListPrice = 24.989999999999998,
                            Price = 22.989999999999998,
                            Price100 = 20.989999999999998,
                            Price50 = 21.989999999999998,
                            Title = "Unbroken"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Walter Isaacson",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Walter Isaacson's definitive biography reveals the life of Apple co-founder Steve Jobs. Through interviews and unparalleled access, it portrays his brilliance, passion, and flaws, offering an intimate look at the visionary who revolutionized technology and culture.",
                            DisplayOrder = 13,
                            ISBN = "978-1-4516-4853-9",
                            IsHidden = false,
                            ListPrice = 26.989999999999998,
                            Price = 24.989999999999998,
                            Price100 = 22.989999999999998,
                            Price50 = 23.989999999999998,
                            Title = "Steve Jobs"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Maurice Sendak",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Maurice Sendak's beloved children's classic follows Max, a young boy who sails to an island of wild creatures. With stunning illustrations and heartfelt storytelling, this imaginative tale of adventure and belonging captivates readers of all ages.",
                            DisplayOrder = 14,
                            ISBN = "978-0-06-025492-6",
                            IsHidden = false,
                            ListPrice = 12.99,
                            Price = 10.99,
                            Price100 = 8.9900000000000002,
                            Price50 = 9.9900000000000002,
                            Title = "Where the Wild Things Are"
                        },
                        new
                        {
                            Id = 15,
                            Author = "William L. Shirer",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "William L. Shirer's monumental history chronicles Nazi Germany's rise and fall. Drawing on firsthand accounts and extensive research, this definitive work offers a chilling, detailed narrative of Hitler's regime and its catastrophic impact on the world.",
                            DisplayOrder = 15,
                            ISBN = "978-1-4516-4592-7",
                            IsHidden = false,
                            ListPrice = 32.990000000000002,
                            Price = 29.989999999999998,
                            Price100 = 27.989999999999998,
                            Price50 = 28.989999999999998,
                            Title = "The Rise and Fall of the Third Reich"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Howard Zinn",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Howard Zinn's groundbreaking history reframes America's past through the lens of ordinary people, minorities, and the oppressed. From Columbus to the present, this influential work challenges traditional narratives, highlighting struggles for justice and equality.",
                            DisplayOrder = 16,
                            ISBN = "978-0-06-083865-2",
                            IsHidden = false,
                            ListPrice = 24.989999999999998,
                            Price = 22.989999999999998,
                            Price100 = 20.989999999999998,
                            Price50 = 21.989999999999998,
                            Title = "A People's History of the United States"
                        },
                        new
                        {
                            Id = 17,
                            Author = "J.R.R. Tolkien",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "J.R.R. Tolkien's enchanting prelude to The Lord of the Rings follows Bilbo Baggins on an unexpected adventure with dwarves and a wizard. This timeless fantasy, rich with mythical creatures and epic quests, laid the foundation for modern fantasy literature.",
                            DisplayOrder = 17,
                            ISBN = "978-0-547-92822-7",
                            IsHidden = false,
                            ListPrice = 19.989999999999998,
                            Price = 17.989999999999998,
                            Price100 = 15.99,
                            Price50 = 16.989999999999998,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 18,
                            Author = "George R.R. Martin",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "George R.R. Martin's epic fantasy launches A Song of Ice and Fire with intricate political intrigue and vivid characters. In a world where seasons last years, noble families vie for the Iron Throne, unaware of ancient threats awakening. A modern fantasy classic.",
                            DisplayOrder = 18,
                            ISBN = "978-0-553-10354-0",
                            IsHidden = false,
                            ListPrice = 23.989999999999998,
                            Price = 21.989999999999998,
                            Price100 = 19.989999999999998,
                            Price50 = 20.989999999999998,
                            Title = "A Game of Thrones"
                        },
                        new
                        {
                            Id = 19,
                            Author = "George R.R. Martin",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "George R.R. Martin's fifth *A Song of Ice and Fire* novel follows Daenerys Targaryen ruling Meereen with her dragons, while Tyrion Lannister flees Westeros and Jon Snow faces threats at the Wall. Packed with intrigue, betrayal, and epic scope, this installment deepens the saga’s complex narrative.",
                            DisplayOrder = 19,
                            ISBN = "978-0-553-80558-1",
                            IsHidden = false,
                            ListPrice = 23.989999999999998,
                            Price = 21.989999999999998,
                            Price100 = 19.989999999999998,
                            Price50 = 20.989999999999998,
                            Title = "A Dance with Dragons"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Bulky.Models.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Bulky.Models.Models.ApplicationUser", b =>
                {
                    b.HasOne("Bulky.Models.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Bulky.Models.Models.Cart", b =>
                {
                    b.HasOne("Bulky.Models.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bulky.Models.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bulky.Models.Models.OrderDetail", b =>
                {
                    b.HasOne("Bulky.Models.Models.OrderHeader", "OrderHeader")
                        .WithMany()
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bulky.Models.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bulky.Models.Models.OrderHeader", b =>
                {
                    b.HasOne("Bulky.Models.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Bulky.Models.Models.Product", b =>
                {
                    b.HasOne("Bulky.Models.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Bulky.Models.Models.ProductImage", b =>
                {
                    b.HasOne("Bulky.Models.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Bulky.Models.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Bulky.Models.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bulky.Models.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Bulky.Models.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bulky.Models.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Bulky.Models.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
